
ENTRY_SIZE = 3

INITIAL_RANGE_START_REGULAR_NUMBER: int = 1
INITIAL_RANGE_END_REGULAR_NUMBER: int = 49
INITIAL_REGULAR_NUMBER_AMOUNT: int = 6
INITIAL_RANGE_SUPER_NUMBER_START: int = 1
INITIAL_RANGE_SUPER_NUMBER_END: int = 9
INITIAL_SUPER_NUMBER_AMOUNT: int = 1